# Generated by Django 5.1.3 on 2024-11-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_alter_produto_imagem_variacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variacao",
            options={"verbose_name": "Variacao", "verbose_name_plural": "Variações"},
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("V", "Variável"), ("S", "Simples")], default="V", max_length=1
            ),
        ),
    ]
