# Generated by Django 5.1.3 on 2024-12-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0004_alter_produto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao_curta",
            field=models.TextField(max_length=255, verbose_name="Descrição curta"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao_longa",
            field=models.TextField(verbose_name="Descrição longa"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing",
            field=models.FloatField(verbose_name="Valor Original"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing_promocional",
            field=models.FloatField(default=0, verbose_name="Valor Promocional"),
        ),
        migrations.AlterField(
            model_name="variacao",
            name="preco",
            field=models.FloatField(verbose_name="Valor Original"),
        ),
        migrations.AlterField(
            model_name="variacao",
            name="preco_promocional",
            field=models.FloatField(default=0, verbose_name="Valor Promocional"),
        ),
    ]
