# Generated by Django 5.1.3 on 2024-12-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="variacao",
            field=models.CharField(default="Sem variação", max_length=255),
        ),
        migrations.AddField(
            model_name="pedido",
            name="qtd_total",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="produto_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="quantidade",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="variacao_id",
            field=models.PositiveIntegerField(),
        ),
    ]
