# Generated by Django 5.1.3 on 2024-12-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_itempedido_variacao_pedido_qtd_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="variacao",
            field=models.CharField(max_length=255),
        ),
    ]
